# Service Config
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins-demo
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: jenkins
  type: LoadBalancer 
  ports:
    - name: httpport
      port: 8080
      targetPort: 8080
    - name: jnlpport
      port: 50000
      targetPort: 50000
